name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  
  push-to-registry:
    runs-on: [ubuntu-latest]
    env:
      WALHALL_SERVER: development-haas-millerandersonrobinson.newapp.io
      GIT_COMMIT: ${{ github.sha }}
      GIT_REF: ${{ github.ref }}
      GIT_REPO: ${{ github.repository }}
    
    steps:
    - name: Push to the registry
      run: echo "Pushing to the registry!"
    - name: Notify Walhall
      run: curl -X POST -H "Accept:application/json" -H "Content-Type:application/json" -d "{\"commit\":\"${{ github.sha }}\", \"branch\":\"${GIT_REF##*/}\"}" https://${WALHALL_SERVER}/orgs/org1/modules/${GIT_REPO##*/}

    
