name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  
  push-to-registry:
    runs-on: [ubuntu-latest]

    
    steps:
    - name: Push to the registry
      run: echo "Pushing to the registry!"
    - name: Notify Walhall
      run: echo "{\"commit\":\"${{ github.sha }}\", \"branch\":\"${{ github.ref }}\"

    
